const fs = require('fs');
let content = fs.readFileSync('src/App.jsx', 'utf8');

const oldPrompt = `You are an expert McKinsey interview coach. Analyze the candidate's response.\nFocus on:\n1. Content: Structured thinking, Top-Down communication, MECE principle.\n2. Tone & Pace: Executive presence, confidence, clarity.\n3. Recommendations: Actionable steps to improve.\n4. Improved Transcript: Rewrite their exact answer to sound more professional, structured, and impactful. Stay as close to the original as possible. Wrap any modified or added words in **bold**.\n\nYou MUST respond in ONLY valid JSON format with exactly these SIX keys:\n{\n  "score": "A score out of 10 (e.g. \'7/10\')",\n  "short_summary": "A 1-sentence overarching summary of their performance.",\n  "content": "Your detailed feedback on structure...",\n  "tone_and_pace": "Your feedback on delivery...",\n  "recommendations": "Your actionable steps...",\n  "improved_transcript": "The rewritten transcript with changes in **bold**."\n}\nDo not output any other text, markdown blocks, or introduction.`;

const newPrompt = `You are an expert McKinsey interview coach. Analyze the candidate's response.\nFocus on:\n1. Content: Structured thinking, Top-Down communication, MECE principle.\n2. Tone & Pace: Executive presence, confidence, clarity.\n3. Recommendations: Actionable steps to improve.\n4. Cleaned Transcript: Clean up the exact answer by removing filler words (ums, ahs, like) and fixing basic grammar. DO NOT change the substance. Wrap any changes in **bold**.\n5. Improved Answer: Rewrite their answer to sound more professional, structured, and impactful. Wrap any modified or added words in **bold**.\n\nYou MUST respond in ONLY valid JSON format with exactly these SEVEN keys:\n{\n  "score": "A score out of 10 (e.g. \'7/10\')",\n  "short_summary": "A 1-sentence overarching summary of their performance.",\n  "content": "Your detailed feedback on structure...",\n  "tone_and_pace": "Your feedback on delivery...",\n  "recommendations": "Your actionable steps...",\n  "cleaned_transcript": "The cleaned up original transcript...",\n  "improved_answer": "The structurally rewritten answer..."\n}\nDo not output any other text, markdown blocks, or introduction.`;

content = content.replace(oldPrompt, newPrompt);

const oldTranscriptBox = `{feedback.improved_transcript && (\n                  <div className="p-4 bg-orange-50 rounded-xl border border-orange-200">\n                    <h3 className="font-bold text-orange-800 mb-2">✨ Improved Transcript</h3>\n                    <p className="text-sm text-gray-800 whitespace-pre-wrap leading-relaxed">\n                      {renderHighlightedText(feedback.improved_transcript)}\n                    </p>\n                  </div>\n                )}`;

const newTranscriptBox = `{feedback.cleaned_transcript && (\n                  <div className="p-4 bg-yellow-50 rounded-xl border border-yellow-200">\n                    <h3 className="font-bold text-yellow-800 mb-2">🧹 Cleaned Transcript</h3>\n                    <p className="text-sm text-gray-800 whitespace-pre-wrap leading-relaxed">\n                      {renderHighlightedText(feedback.cleaned_transcript)}\n                    </p>\n                  </div>\n                )}`;

content = content.replace(oldTranscriptBox, newTranscriptBox);

const oldAnswerBox = `{feedback.improved_transcript && (\n                  <div className="p-4 bg-orange-50 rounded-xl border border-orange-200 col-span-1 md:col-span-2">\n                    <h3 className="font-bold text-orange-800 mb-2">✨ Improved Answer</h3>\n                    <p className="text-sm text-gray-800 whitespace-pre-wrap leading-relaxed">\n                      {renderHighlightedText(feedback.improved_transcript)}\n                    </p>\n                  </div>\n                )}`;

const newAnswerBox = `{(feedback.improved_answer || feedback.improved_transcript) && (\n                  <div className="p-4 bg-orange-50 rounded-xl border border-orange-200 col-span-1 md:col-span-2">\n                    <h3 className="font-bold text-orange-800 mb-2">✨ Improved Answer</h3>\n                    <p className="text-sm text-gray-800 whitespace-pre-wrap leading-relaxed">\n                      {renderHighlightedText(feedback.improved_answer || feedback.improved_transcript)}\n                    </p>\n                  </div>\n                )}`;

content = content.replace(oldAnswerBox, newAnswerBox);

const oldHistoryBox = `{entry.feedback && entry.feedback.improved_transcript && (\n                        <div className="bg-orange-50 text-orange-800 p-3 rounded-lg text-sm border border-orange-200 mt-3 mb-4">\n                          <p className="font-bold mb-1">✨ Improved Answer:</p>\n                          <p className="whitespace-pre-wrap leading-relaxed text-sm">\n                             {renderHighlightedText(entry.feedback.improved_transcript)}\n                          </p>\n                        </div>\n                      )}`;

const newHistoryBox = `{entry.feedback && entry.feedback.cleaned_transcript && (\n                        <div className="bg-yellow-50 text-yellow-800 p-3 rounded-lg text-sm border border-yellow-200 mt-3 mb-4">\n                          <p className="font-bold mb-1">🧹 Cleaned Transcript:</p>\n                          <p className="whitespace-pre-wrap leading-relaxed text-sm">\n                             {renderHighlightedText(entry.feedback.cleaned_transcript)}\n                          </p>\n                        </div>\n                      )}\n\n                      {entry.feedback && (entry.feedback.improved_answer || entry.feedback.improved_transcript) && (\n                        <div className="bg-orange-50 text-orange-800 p-3 rounded-lg text-sm border border-orange-200 mt-3 mb-4">\n                          <p className="font-bold mb-1">✨ Improved Answer:</p>\n                          <p className="whitespace-pre-wrap leading-relaxed text-sm">\n                             {renderHighlightedText(entry.feedback.improved_answer || entry.feedback.improved_transcript)}\n                          </p>\n                        </div>\n                      )}`;

content = content.replace(oldHistoryBox, newHistoryBox);

fs.writeFileSync('src/App.jsx', content);
console.log("File updated successfully!");
